# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=default
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),default)
  test_server_config = default
  SCL_config = default
endif

PROJECTS := test_server SCL

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

test_server: SCL
ifneq (,$(test_server_config))
	@echo "==== Building test_server ($(test_server_config)) ===="
	@${MAKE} --no-print-directory -C . -f test_server.make config=$(test_server_config)
endif

SCL:
ifneq (,$(SCL_config))
	@echo "==== Building SCL ($(SCL_config)) ===="
	@${MAKE} --no-print-directory -C . -f SCL.make config=$(SCL_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f test_server.make clean
	@${MAKE} --no-print-directory -C . -f SCL.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  default"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   test_server"
	@echo "   SCL"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"